# -*- coding: utf-8 -*-
"""Cópia de Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIh6iHqkRYZWJG0At9-pWm9wvDOcDQi4

Calculadora
"""

while True:

   num1 = float(input("Digite o primeiro número: "))
   operacao = input("Digite a operação (+, -, /, *, **, p%)")
   num2 = float(input("Digite o segundo número: "))

   if operacao == "+":
     print(f"O resultado de {num1} + {num2} é: {num1 + num2}")
   elif operacao == "-":
     print(f"O resultado de {num1} - {num2} é: {num1 - num2}")
   elif operacao == "/":
      if num2 == 0:
        print("Não é possível dividir por zero")
      else:
        print(f"O resultado de {num1} / {num2} é: {num1 / num2}")
   elif operacao == "p%":
     print(f"O resultado de {num1}% de {num2} é: {(num1 / 100) * num2}")
   elif operacao == "*":
     print(f"O resultado de {num1} * {num2} é: {num1 * num2}")
   elif operacao == "**":
     print(f"O resultado de {num1} ** {num2} é: {num1 ** num2}")
   else:
     print("Operação inválida")

   continuar = input("Deseja continuar? (sim/não)")
   if continuar.lower() != "sim":
     break
print("Calculadora encerrada!")